mavtables: IPAddress Class Reference
IPAddress Class Reference
#include <IPAddress.hpp>
Public Member Functions
IPAddress (const IPAddress &other)=default
IPAddress (const IPAddress &other, unsigned int port)
IPAddress (unsigned long address, unsigned int port=0)
IPAddress (std::string address)
unsigned long address () const
unsigned int port () const
IPAddress & operator= (const IPAddress &other)=default
Friends
std::ostream & operator<< (std::ostream &os, const IPAddress &ipaddress)
Related Functions
(Note that these are not member functions.)
bool operator== (const IPAddress &lhs, const IPAddress &rhs)
bool operator!= (const IPAddress &lhs, const IPAddress &rhs)
bool operator< (const IPAddress &lhs, const IPAddress &rhs)
bool operator> (const IPAddress &lhs, const IPAddress &rhs)
bool operator<= (const IPAddress &lhs, const IPAddress &rhs)
bool operator>= (const IPAddress &lhs, const IPAddress &rhs)
IPAddress dnslookup (const std::string &url)
Detailed Description
An IP address with optional port number.
Definition at line 30 of file IPAddress.hpp.
Constructor & Destructor Documentation
IPAddress() [1/4]
IPAddress::IPAddress (const IPAddress & other) default
Copy constructor.
Parameters
other IP address to copy.
IPAddress() [2/4]
IPAddress::IPAddress (const IPAddress & other, unsigned int port)
Construct IP from another IP address, changing the port number.
Copy constructor that also changes the port.
Parameters
other IP address to copy from.
port Port number (0 - 65535). A port of 0 means no specific port.
Exceptions
std::out_of_range If the port number is out of range.
Definition at line 76 of file IPAddress.cpp.
 {
     construct_(other.address_, port);
 }
IPAddress() [3/4]
IPAddress::IPAddress (unsigned long address, unsigned int port = 0)
Construct IP address from address and port number.
Parameters
address 32-bit IP address in system byte order (0x00000000 - 0xFFFFFFFF).
port Port number (0 - 65535). A port of 0 means no specific port.
Exceptions
std::out_of_range If the address or port number is out of range.
Definition at line 89 of file IPAddress.cpp.
 {
     construct_(address, port);
 }
IPAddress() [4/4]
IPAddress::IPAddress (std::string address)
Construct IP address from a string.
Parse a string of the form "<IP Address>" or "<IP Address>:<Port Number>".
Some examples are:
"127.0.0.1"
"127.0.0.1:8888"
"183.125.120.42:443"
If no port is given the 0 port is used which represents no specific port.
Parameters
address String representing the IP address and optionally the port number.
Exceptions
std::invalid_argument If the string does not represent a valid IP address.
std::out_of_range If an address octet or the port number is out of range.
Definition at line 113 of file IPAddress.cpp.
 {
     // Separate port from address.
     unsigned int port = 0;
     std::vector<std::string> parts;
     boost::split(parts, address, [](char c)
     {
         return c == ':';
     });
     // Read port.
     if (parts.size() == 2)
     {
         std::istringstream(parts.back()) >> port;
         parts.pop_back();
     }
     if (parts.size() != 1)
     {
         throw std::invalid_argument("Invalid IP address string.");
     }
     address = parts.back();
     // Check validity of address string.
     if (address.size() < 7 || !(isdigit(address.front()))
             || !isdigit(address.back()))
     {
         throw std::invalid_argument("Invalid IP address string.");
     }
     for (auto c : address)
     {
         if (!(c == '.' || isdigit(c)))
         {
             throw std::invalid_argument("Invalid IP address string.");
         }
     }
     // Read address.
     std::replace(address.begin(), address.end(), '.', ' ');
     std::vector<unsigned long> octets;
     std::istringstream ss(address);
     unsigned long octet;
     while (ss >> octet)
     {
         octets.push_back(octet);
     }
     // Ensure proper number of octets.
     if (octets.size() != 4)
     {
         throw std::invalid_argument("Invalid IP address string.");
     }
     // Ensure octets are between 0 and 255.
     for (auto i : octets)
         if (i > 255)
         {
             throw std::out_of_range("address octet (" + std::to_string(i) +
                                     ") is outside of the allowed range (0 - 255).");
         }
     {
     }
     construct_((octets[0] << 8 * 3) | (octets[1] << 8 * 2) |
                (octets[2] << 8) | octets[3], port);
 }
Member Function Documentation
address()
unsigned long IPAddress::address () const
Return the IP address.
Returns
The 32-bit IP address (in system byte order) as an integer (0x00000000 - 0xFFFFFFFF).
Definition at line 190 of file IPAddress.cpp.
 {
     return address_;
 }
operator=()
IPAddress& IPAddress::operator= (const IPAddress & other) default
Assignment operator.
Parameters
other IP address to copy.
port()
unsigned int IPAddress::port () const
Return the port.
Returns
The port number (0 - 65535).
Definition at line 200 of file IPAddress.cpp.
 {
     return port_;
 }
Friends And Related Function Documentation
dnslookup()
IPAddress dnslookup (const std::string & url) related
Lookup an IP address based on a hostname.
Parameters
url The URL to get an IP address for.
Returns
IP addresses corrensponding to the given URL.
Exceptions
DNSLookupError If the address cannot be found.
Definition at line 341 of file IPAddress.cpp.
References IPAddress(), and port().
 {
     #ifdef UNIX
     return unix_dnslookup(url, 0);
     #elif WINDOWS
     return win32_dnslookup(url, 0);
     #endif
 }
operator!=()
bool operator!= (const IPAddress & lhs, const IPAddress & rhs) related
Inequality comparison.
Parameters
lhs The left hand side IP address.
rhs The right hand side IP address.
Return values
true if lhs and rhs do not have the same address and port.
false if lhs and rhs have the same address and port.
Definition at line 228 of file IPAddress.cpp.
References address(), and port().
 {
     return (lhs.address() != rhs.address()) || (lhs.port() != rhs.port());
 }
operator<()
bool operator< (const IPAddress & lhs, const IPAddress & rhs) related
Less than comparison.
Note
The address is considered first followed by the port.
Parameters
lhs The left hand side IP address.
rhs The right hand side IP address.
Return values
true if lhs is less than rhs.
false if lhs is not less than rhs.
Definition at line 244 of file IPAddress.cpp.
References address(), and port().
 {
     return (lhs.address() < rhs.address()) || ((lhs.address() == rhs.address())
             && (lhs.port() < rhs.port()));
 }
operator<<
std::ostream& operator<< (std::ostream & os, const IPAddress & ipaddress) friend
Print the IP address to the given output stream.
The format is "<IP Address>" or "<IP Address>:<Port Number>" if the port number is nonzero an "<IP Address>" if the port is 0.
Some examples are:
"127.0.0.1"
"127.0.0.1:8888"
"183.125.120.42:443"
Parameters
os The output stream to print to.
ipaddress The IP address to print.
Returns
The output stream.
Definition at line 314 of file IPAddress.cpp.
 {
     const auto bytes = to_bytes(ipaddress.address_);
     for (size_t i = 3; i > 0; --i)
     {
         os << static_cast<int>(bytes[i]) << ".";
     }
     os << static_cast<int>(bytes[0]);
     if (ipaddress.port_ != 0)
     {
         os << ":" << ipaddress.port_;
     }
     return os;
 }
operator<=()
bool operator<= (const IPAddress & lhs, const IPAddress & rhs) related
Less than or equal comparison.
Note
The address is considered first followed by the port.
Parameters
lhs The left hand side IP address.
rhs The right hand side IP address.
Return values
true if lhs is less than or eqaul to rhs.
false if lhs is greater than rhs.
Definition at line 278 of file IPAddress.cpp.
 {
     return (lhs < rhs) || (lhs == rhs);
 }
operator==()
bool operator== (const IPAddress & lhs, const IPAddress & rhs) related
Equality comparison.
Parameters
lhs The left hand side IP address.
rhs The right hand side IP address.
Return values
true if lhs and rhs have the same address and port.
false if lhs and rhs do not have the same address and port.
Definition at line 214 of file IPAddress.cpp.
References address(), and port().
 {
     return (lhs.address() == rhs.address()) && (lhs.port() == rhs.port());
 }
operator>()
bool operator> (const IPAddress & lhs, const IPAddress & rhs) related
Greater than comparison.
Note
The address is considered first followed by the port.
Parameters
lhs The left hand side IP address.
rhs The right hand side IP address.
Return values
true if lhs is greater than rhs.
false if lhs is not greater than rhs.
Definition at line 261 of file IPAddress.cpp.
References address(), and port().
 {
     return (lhs.address() > rhs.address()) || ((lhs.address() == rhs.address())
             && (lhs.port() > rhs.port()));
 }
operator>=()
bool operator>= (const IPAddress & lhs, const IPAddress & rhs) related
Greater than comparison.
Note
The address is considered first followed by the port.
Parameters
lhs The left hand side IP address.
rhs The right hand side IP address.
Return values
true if lhs is greater than or equal to rhs.
false if lhs is less than rhs.
Definition at line 294 of file IPAddress.cpp.
 {
     return (lhs > rhs) || (lhs == rhs);
 }
The documentation for this class was generated from the following files:
IPAddress.hpp
IPAddress.cpp