mavtables: MAVAddress Class Reference
MAVAddress Class Reference
#include <MAVAddress.hpp>
Public Member Functions
MAVAddress (const MAVAddress &other)=default
MAVAddress (unsigned int address)
MAVAddress (unsigned int system, unsigned int component)
MAVAddress (std::string address)
unsigned int address () const
unsigned int system () const
unsigned int component () const
MAVAddress & operator= (const MAVAddress &other)=default
Related Functions
(Note that these are not member functions.)
bool operator== (const MAVAddress &lhs, const MAVAddress &rhs)
bool operator!= (const MAVAddress &lhs, const MAVAddress &rhs)
bool operator< (const MAVAddress &lhs, const MAVAddress &rhs)
bool operator> (const MAVAddress &lhs, const MAVAddress &rhs)
bool operator<= (const MAVAddress &lhs, const MAVAddress &rhs)
bool operator>= (const MAVAddress &lhs, const MAVAddress &rhs)
std::ostream & operator<< (std::ostream &os, const MAVAddress &mavaddress)
Detailed Description
A MAVLink address.
MAVLink addresses consist of a system and component and can be represented as two ocetets in the form:
system.component
Therefore, a system of 16 and a component of 8 can be represented as 16.8.
0.0 is reserved as the broadcast address.
Definition at line 36 of file MAVAddress.hpp.
Constructor & Destructor Documentation
MAVAddress() [1/4]
MAVAddress::MAVAddress (const MAVAddress & other) default
Copy constructor.
Parameters
other MAVLink address to copy.
MAVAddress() [2/4]
MAVAddress::MAVAddress (unsigned int address)
Construct MAVLink address from an address in numeric representation.
The numeric representation of a MAVLink address is two bytes, the MSB contains the System ID and the LSB contains the Component ID.
Parameters
address Address (0 - 65535) with System encoded in MSB and Component encoded in LSB.
Exceptions
std::out_of_range if the address is not between 0 and 65535.
Definition at line 40 of file MAVAddress.cpp.
References address(), component(), and system().
 {
     if (address > 65535)
     {
         throw std::out_of_range("address (" + std::to_string(address) +
                                 ") is outside of the allowed range (0 - 65535).");
     }
     address_ = address;
 }
MAVAddress() [3/4]
MAVAddress::MAVAddress (unsigned int system, unsigned int component)
Construct MAVLink address from the System ID and Component ID.
Note
component=0 and system=0 is the broadcast address.
Parameters
system System ID (0 - 255).
component Component ID (0 - 255).
Exceptions
std::out_of_range if either the System ID or the component ID is out of range.
Definition at line 80 of file MAVAddress.cpp.
 {
     construct_(system, component);
 }
MAVAddress() [4/4]
MAVAddress::MAVAddress (std::string address)
Construct MAVLink address from a string.
Parse a string of the form "<System ID>.<Component ID>".
Some examples are:
"0.0"
"16.8"
"128.4"
Parameters
address String representing the MAVLink address.
Definition at line 97 of file MAVAddress.cpp.
 {
     // Check validity of address string.
     if (address.size() < 3 || !(isdigit(address.front()))
             || !isdigit(address.back()))
     {
         throw std::invalid_argument("Invalid MAVLink address string.");
     }
     for (auto c : address)
     {
         if (!(c == '.' || isdigit(c)))
         {
             throw std::invalid_argument("Invalid MAVLink address string.");
         }
     }
     // Read address string.
     std::replace(address.begin(), address.end(), '.', ' ');
     std::vector<unsigned int> octets;
     std::istringstream ss(address);
     unsigned int i;
     while (ss >> i)
     {
         octets.push_back(i);
     }
     // Check for correct number of octets.
     if (octets.size() != 2 || !ss.eof())
     {
         throw std::invalid_argument("Invalid MAVLink address string.");
     }
     construct_(octets[0], octets[1]);
 }
Member Function Documentation
address()
unsigned int MAVAddress::address () const
Return the MAVLink address in numeric form.
Returns
The MAVLink address as a two byte number with the System ID encoded in the MSB and the Component ID in the LSB.
Definition at line 140 of file MAVAddress.cpp.
 {
     return address_;
 }
component()
unsigned int MAVAddress::component () const
Return the Component ID.
Returns
The Component ID (0 - 255).
Definition at line 160 of file MAVAddress.cpp.
 {
     return address_ & 0x00FF;
 }
operator=()
MAVAddress& MAVAddress::operator= (const MAVAddress & other) default
Assignment operator.
Parameters
other MAVLink address to copy.
system()
unsigned int MAVAddress::system () const
Return the System ID.
Returns
The System ID (0 - 255).
Definition at line 150 of file MAVAddress.cpp.
 {
     return (address_ >> 8) & 0x00FF;
 }
Friends And Related Function Documentation
operator!=()
bool operator!= (const MAVAddress & lhs, const MAVAddress & rhs) related
Equality comparison.
Parameters
lhs The left hand side MAVLink address.
rhs The right hand side MAVLink address.
Return values
true if lhs and rhs do not have the same system and component ID's
false if lhs and rhs have the same system and component ID's.
Definition at line 190 of file MAVAddress.cpp.
References address().
 {
     return lhs.address() != rhs.address();
 }
operator<()
bool operator< (const MAVAddress & lhs, const MAVAddress & rhs) related
Less than comparison.
Note
The System ID is considered first followed by the Component ID.
Parameters
lhs The left hand side MAVLink address.
rhs The right hand side MAVLink address.
Return values
true if lhs is less than rhs.
false if lhs is not less than rhs.
Definition at line 206 of file MAVAddress.cpp.
References address().
 {
     return lhs.address() < rhs.address();
 }
operator<<()
std::ostream & operator<< (std::ostream & os, const MAVAddress & mavaddress) related
Print the MAVLink address to the given output stream.
The format is "<System ID>.<Component ID>".
Some examples are:
"0.0"
"16.8"
"128.4"
Parameters
os The output stream to print to.
mavaddress The MAVLink address to print.
Returns
The output stream.
Definition at line 274 of file MAVAddress.cpp.
References component(), and system().
 {
     os << mavaddress.system() << "." << mavaddress.component();
     return os;
 }
operator<=()
bool operator<= (const MAVAddress & lhs, const MAVAddress & rhs) related
Less than or equal comparison.
Note
The System ID is considered first followed by the Component ID.
Parameters
lhs The left hand side IP address.
rhs The right hand side IP address.
Return values
true if lhs is less than or eqaul to rhs.
false if lhs is greater than rhs.
Definition at line 238 of file MAVAddress.cpp.
References address().
 {
     return lhs.address() <= rhs.address();
 }
operator==()
bool operator== (const MAVAddress & lhs, const MAVAddress & rhs) related
Equality comparison.
Parameters
lhs The left hand side MAVLink address.
rhs The right hand side MAVLink address.
Return values
true if lhs and rhs have the same system and component ID's.
false if lhs and rhs do not have the same system and component ID's.
Definition at line 175 of file MAVAddress.cpp.
References address().
 {
     return lhs.address() == rhs.address();
 }
operator>()
bool operator> (const MAVAddress & lhs, const MAVAddress & rhs) related
Greater than comparison.
Note
The System ID is considered first followed by the Component ID.
Parameters
lhs The left hand side MAVLink address.
rhs The right hand side IP address.
Return values
true if lhs is greater than rhs.
false if lhs is not greater than rhs.
Definition at line 222 of file MAVAddress.cpp.
References address().
 {
     return lhs.address() > rhs.address();
 }
operator>=()
bool operator>= (const MAVAddress & lhs, const MAVAddress & rhs) related
Greater than comparison.
Note
The System ID is considered first followed by the Component ID.
Parameters
lhs The left hand side IP address.
rhs The right hand side IP address.
Return values
true if lhs is greater than or equal to rhs.
false if lhs is less than rhs.
Definition at line 254 of file MAVAddress.cpp.
References address().
 {
     return lhs.address() >= rhs.address();
 }
The documentation for this class was generated from the following files:
MAVAddress.hpp
MAVAddress.cpp